version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=hoteldbuser
      - POSTGRES_PASSWORD=hoteldbpassword
      - POSTGRES_DB=hoteldb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://hoteldbuser:hoteldbpassword@postgres:5432/hoteldb?schema=public
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    links:
      - postgres
    entrypoint: ./docker-entrypoint.sh
volumes:
  postgres: