version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=hoteldbuser
      - POSTGRES_PASSWORD=hoteldbpassword
      - POSTGRES_DB=hoteldb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: